name: Daily Loyverse Scraping

on:
  schedule:
    - cron: '0 0 * * *'   # 08:00 AM MYT
  workflow_dispatch:      # Allows manual triggering from GitHub interface

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
    - name: Set up timezone
      run: |
        sudo timedatectl set-timezone Asia/Kuala_Lumpur
        
    - name: Install Chromium and ChromeDriver
      run: |
        # Update package lists
        sudo apt-get update
        
        # Install Chromium and ChromeDriver from Ubuntu repositories
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
        # Verify installations
        echo "Installed Chromium version:"
        chromium-browser --version
        echo "Installed ChromeDriver version:"
        chromedriver --version
        
        # Set browser binary location for Selenium
        echo "CHROME_BINARY_PATH=/usr/bin/chromium-browser" >> $GITHUB_ENV
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        # First install blinker explicitly
        pip install blinker==1.6.3
        # Then install other requirements
        pip install -r requirements.txt
        # Verify installations
        pip list
    
    - name: Verify selenium-wire installation
      run: |
        python -c "import seleniumwire.webdriver; print('selenium-wire successfully imported')"
        
    - name: Run scraper
      env:
        LOYVERSE_ACCOUNTS: ${{ secrets.LOYVERSE_ACCOUNTS }}
        TWOCAPTCHA_API_KEY: ${{ secrets.TWOCAPTCHA_API_KEY }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        HEADLESS: "true"
      run: |
        python -m src.scraper

    # - name: Send email with Excel report
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 587
    #     username: ${{ secrets.EMAIL_USERNAME }}
    #     password: ${{ secrets.EMAIL_PASSWORD }}
    #     subject: Loyverse Daily Report - ${{ steps.date.outputs.date }}
    #     body: |
    #       Daily Loyverse sales report is attached.

    #       This report was automatically generated by GitHub Actions.
    #       Date: ${{ steps.date.outputs.date }}
    #     to: ${{ secrets.EMAIL_RECIPIENTS }}
    #     from: Loyverse Robot <${{ secrets.EMAIL_USERNAME }}>
    #     attachments: ./barHarian_${{ steps.date.outputs.date }}.xlsx

    - name: Upload Excel report as artifact
      if: always()  # Upload even if email sending fails
      uses: actions/upload-artifact@v4
      with:
        name: loyverse-report-${{ steps.date.outputs.date }}
        path: barHarian_*.xlsx
        retention-days: 7  # Keep reports for a week
        compression-level: 6  # Balance between size and speed
        overwrite: true  # Replace any existing artifact with same name

    - name: Handle failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ⚠️ Loyverse Scraper Failed - ${{ steps.date.outputs.date }}
        body: |
          The Loyverse scraper failed to run.
          
          Repository: ${{ github.repository }}
          Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          Please check the GitHub Actions logs for more details.
        to: ${{ secrets.EMAIL_RECIPIENTS }}
        from: Loyverse Robot <${{ secrets.EMAIL_USERNAME }}>